# Generated by Django 3.0.8 on 2020-07-19 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200719_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watched',
            name='user',
        ),
        migrations.AddField(
            model_name='watched',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
