# Generated by Django 3.0.8 on 2020-07-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200719_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watched',
        ),
    ]
