# Generated by Django 3.0.8 on 2020-07-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channelName',
            field=models.CharField(max_length=25),
        ),
    ]
