# Generated by Django 3.0.8 on 2020-07-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200714_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='end',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='start',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
