# Generated by Django 3.0.8 on 2020-07-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200714_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.Platform'),
        ),
    ]
