# Generated by Django 3.0.8 on 2020-07-21 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20200719_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='watched',
            name='ip',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='watched',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
