# Generated by Django 3.0.8 on 2020-07-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200721_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browser',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
